# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 560c97099a1efe924516136566f5ee87890f0ae729a54ea4ecf555dda17912e212a7d08ddb81282e98550bcd6b168a2b2aff4495fc7739fe5d615bc9d4750894

test:
  secret_key_base: 9c3406a355481314afade7f0ef2a28b4066fd37763b509762c13f771504262a4e687ffb1b570b3a8f7283ff58608c5c2098643a14d49f5b2c8d561ce97809aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
